render nodes and links using bfs
callmedhh/react-d3-graph pull request #3
Opened 2020-11-05 06:27 UTC by callmedhh

2020-11-05 07:06 UTC, zhnzhzz approved these changes

2020-11-06 05:28 UTC, TisnKu requested changes

2020-11-06 05:28 UTC, TisnKu commented on src/components/graph/graph.renderer.jsx
> +    elements.push(_renderNode(nodes, startNodeId, config, nodeCallbacks, highlightedNode, highlightedLink, transform));
We can pass a closure function nodeRenderer to avoid passing too many args.

2020-11-06 09:21 UTC, TisnKu approved these changes

2020-11-06 09:24 UTC, merged